# Generated by Django 4.2.3 on 2023-10-20 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome Cliente')),
                ('last_name', models.CharField(max_length=50, verbose_name='Número Pedido')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('show', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/%Y/%m')),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Em atendimento', 'Em atendimento'), ('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Novo', max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('inicio_atendimento', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, choices=[('loja', 'Loja'), ('sap', 'Sap'), ('chat', 'Chat'), ('RA', 'Ra'), ('whats', 'Whats'), ('Ligação', 'Ligação')], max_length=20, null=True)),
                ('description_store', models.TextField(blank=True, verbose_name='Obs Loja')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sacs.category', verbose_name='Categoria')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Loja')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacs.contact')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
