# Generated by Django 4.2.1 on 2023-06-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_satisfacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pedido2',
            field=models.CharField(default='123456', max_length=255),
        ),
    ]
