# Generated by Django 4.2.1 on 2023-06-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_satisfacao', '0002_feedback_pedido2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='pedido2',
            new_name='pedido',
        ),
    ]
