# Generated by Django 4.2.1 on 2023-06-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_satisfacao', '0003_rename_pedido2_feedback_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default='2023-06-22 16:33:24'),
        ),
    ]
