# Generated by Django 4.2.1 on 2023-06-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_satisfacao', '0005_alter_feedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.CharField(default='2023-06-22 16:44:45', max_length=19),
        ),
    ]
