# Generated by Django 4.2.3 on 2023-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_satisfacao', '0014_feedback_data_pedido_feedback_loja_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.CharField(default='2023-10-20 14:56:41', max_length=19),
        ),
    ]
