# Generated by Django 4.2.3 on 2023-10-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ava', models.DateTimeField(blank=True, null=True, verbose_name='Data Avaliação')),
                ('medias_subtopicos', models.JSONField(blank=True, default=dict, null=True, verbose_name='Médias por Subtópico')),
                ('media_geral', models.FloatField(blank=True, null=True, verbose_name='Média Geral')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
                ('peso', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, choices=[('Coordenador', 'Coordenador'), ('Supervisor', 'Supervisor'), ('Gerente', 'Gerente'), ('Líder de Pista', 'Líder de Pista'), ('Líder de Loja', 'Líder de Loja'), ('Frentista', 'Frentista'), ('Operador de Caixa', 'Operador de Caixa'), ('Lubrificador', 'Lubrificador'), ('Atendente de Loja', 'Atendente de Loja')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Avaliação',
                'verbose_name_plural': 'Tipo Avaliações',
            },
        ),
        migrations.CreateModel(
            name='UserPosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Coordenador', 'Coordenador'), ('Supervisor', 'Supervisor'), ('Gerente', 'Gerente'), ('Líder de Pista', 'Líder de Pista'), ('Líder de Loja', 'Líder de Loja'), ('Frentista', 'Frentista'), ('Operador de Caixa', 'Operador de Caixa'), ('Lubrificador', 'Lubrificador'), ('Atendente de Loja', 'Atendente de Loja')], default='', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('pode_avaliar', models.BooleanField(default=False)),
                ('grupos', models.ManyToManyField(blank=True, related_name='usuarios_grupos', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário Posto',
                'verbose_name_plural': 'Usuários Postos',
            },
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, choices=[('Atendimento ao Cliente', 'Atendimento ao Cliente'), ('Reponsabilidade', 'Reponsabilidade'), ('Orientação para Resultados', 'Orientação para Resultados'), ('Habilidades Interpessoais', 'Habilidades Interpessoais'), ('Comunicação', 'Comunicação'), ('Conhecimento Específico', 'Conhecimento Específico'), ('Organização e Planejamento', 'Organização e Planejamento'), ('Orientação para Qualidade', 'Orientação para Qualidade')], max_length=255, null=True)),
                ('tipo_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto_condor.tipoavaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.FloatField(choices=[(1.0, 'Atende'), (0.0, 'Não atende')])),
                ('avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto_condor.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto_condor.questao')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='subtopico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto_condor.subtopico'),
        ),
        migrations.CreateModel(
            name='MediaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FloatField()),
                ('avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto_condor.avaliacao')),
                ('subtopico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto_condor.subtopico')),
            ],
            options={
                'verbose_name': 'Média Avaliação',
                'verbose_name_plural': 'Média Avaliações',
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='user_posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto_condor.userposto'),
        ),
    ]
