# Generated by Django 4.2.3 on 2023-11-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto_condor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='Loja',
            field=models.CharField(blank=True, null=True, verbose_name='Loja'),
        ),
    ]
