# Generated by Django 4.2.3 on 2023-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto_condor', '0002_avaliacao_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='cargo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cargo'),
        ),
    ]
