# Generated by Django 4.2.3 on 2023-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto_condor', '0005_avaliacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopico',
            name='nome',
            field=models.CharField(blank=True, choices=[('Atendimento ao Cliente', 'Atendimento ao Cliente'), ('Responsabilidade', 'Responsabilidade'), ('Orientação para Resultados', 'Orientação para Resultados'), ('Habilidades Interpessoais', 'Habilidades Interpessoais'), ('Comunicação', 'Comunicação'), ('Conhecimento Específico', 'Conhecimento Específico'), ('Organização e Planejamento', 'Organização e Planejamento'), ('Orientação para Qualidade', 'Orientação para Qualidade'), ('Orientação para Pessoas', 'Orientação para Pessoas'), ('Segurança', 'Segurança')], max_length=255, null=True),
        ),
    ]
