# Generated by Django 4.2.3 on 2024-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto_condor', '0007_alter_avaliacao_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='last',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
